-- ============================================================================
-- Consuntiver - schema del database
-- Dialetto: PostgreSQL (produzione). In H2 (sviluppo) la stessa DDL e' valida;
-- cambia solo la precisione dei timestamp (H2 usa timestamp(9)).
-- Lo schema in app e' generato da Hibernate (ddl-auto=update): questo file
-- documenta le tabelle e serve per crearle a mano o con migrazioni (es. Flyway).
-- Creare le tabelle nell'ordine indicato per rispettare le foreign key.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Utenti
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username)
);

-- ---------------------------------------------------------------------------
-- Configurazione per utente (1:1): home ed URL base per i link ai task
-- ---------------------------------------------------------------------------
CREATE TABLE user_config (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL,
    home_url      VARCHAR(500) NOT NULL,
    task_base_url VARCHAR(500) NOT NULL,
    CONSTRAINT uk_user_config_user UNIQUE (user_id),
    CONSTRAINT fk_user_config_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ---------------------------------------------------------------------------
-- Righe di attivita' ("cose che faccio"): inizio, fine e descrizione
--   created_at = inizio (scritto alla creazione della riga)
--   ended_at   = fine (valorizzata all'inserimento della riga successiva; NULL = in corso)
-- ---------------------------------------------------------------------------
CREATE TABLE work_entries (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    ended_at    TIMESTAMP(6) WITH TIME ZONE,
    description VARCHAR(2000) NOT NULL,
    user_id     BIGINT NOT NULL,
    CONSTRAINT fk_work_entries_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ---------------------------------------------------------------------------
-- Timbrature (Inizio / Pausa / Fine)
--   clock_out NULL = sessione ancora aperta ("in servizio")
-- ---------------------------------------------------------------------------
CREATE TABLE attendances (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clock_in  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    clock_out TIMESTAMP(6) WITH TIME ZONE,
    user_id   BIGINT NOT NULL,
    CONSTRAINT fk_attendances_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ---------------------------------------------------------------------------
-- Task fissi per anno (es. manutenzioni annuali)
--   task_number opzionale: se presente costruisce il link a Easy
-- ---------------------------------------------------------------------------
CREATE TABLE fixed_tasks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_number VARCHAR(255),
    description VARCHAR(1000) NOT NULL,
    task_year   INTEGER NOT NULL,
    user_id     BIGINT NOT NULL,
    CONSTRAINT fk_fixed_tasks_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ---------------------------------------------------------------------------
-- Indici consigliati (opzionali) per le query piu' frequenti
-- ---------------------------------------------------------------------------
CREATE INDEX idx_work_entries_user_started ON work_entries (user_id, created_at);
CREATE INDEX idx_work_entries_user_open    ON work_entries (user_id, ended_at);
CREATE INDEX idx_attendances_user_clockin  ON attendances (user_id, clock_in);
CREATE INDEX idx_fixed_tasks_user          ON fixed_tasks (user_id);
