-- ---------------------------------------------------------------------------
-- Utenti registrati
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50)  NOT NULL,
    password   VARCHAR(255) NOT NULL,          -- hash BCrypt
    email      VARCHAR(255),                   -- facoltativo
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email    UNIQUE (email)
);

-- ---------------------------------------------------------------------------
-- Task riutilizzabili (per-utente, con anno di validita').
--   cod_task = numero del ticket sul portale (es. 129671), facoltativo
--   I task possono essere creati a mano (task fissi) o automaticamente quando
--   un'attivita' cita un #codice non ancora presente.
-- ---------------------------------------------------------------------------
CREATE TABLE task (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user     BIGINT       NOT NULL,
    cod_task    VARCHAR(50),
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    year        INTEGER      NOT NULL,
    CONSTRAINT fk_task_user FOREIGN KEY (id_user) REFERENCES users (id)
);

-- Evita duplicati automatici dello stesso ticket per utente/anno
-- (solo quando il codice e' valorizzato).
CREATE UNIQUE INDEX uk_task_user_cod_year
    ON task (id_user, cod_task, year) WHERE cod_task IS NOT NULL;

CREATE INDEX idx_task_user_year ON task (id_user, year);

-- ---------------------------------------------------------------------------
-- Attivita' = le righe principali (interruzioni giornaliere).
--   start_at = inizio (alla creazione), end_at = fine (NULL = in corso)
--   id_task  = task collegato (NULL per righe senza task, es. "Pausa pranzo")
-- ---------------------------------------------------------------------------
CREATE TABLE activity (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user     BIGINT        NOT NULL,
    id_task     BIGINT,
    start_at    TIMESTAMPTZ   NOT NULL,
    end_at      TIMESTAMPTZ,
    description VARCHAR(2000) NOT NULL,
    CONSTRAINT fk_activity_user FOREIGN KEY (id_user) REFERENCES users (id),
    CONSTRAINT fk_activity_task FOREIGN KEY (id_task) REFERENCES task (id)
);

CREATE INDEX idx_activity_user_start ON activity (id_user, start_at);
CREATE INDEX idx_activity_user_open  ON activity (id_user, end_at);
CREATE INDEX idx_activity_task       ON activity (id_task);

-- ---------------------------------------------------------------------------
-- Giornata lavorativa: i quattro orari inseriti a mano che alimentano il timer
-- delle 8 ore (lavoro netto, esclusa la pausa pranzo). Una riga per utente/giorno.
--   entry_at       = orario di entrata (avvia il timer)
--   lunch_start_at = inizio pausa pranzo
--   lunch_end_at   = rientro dalla pausa pranzo
--   exit_at        = orario di uscita
-- Gli orari possono essere NULL finche' non vengono registrati.
-- ---------------------------------------------------------------------------
CREATE TABLE work_session (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user        BIGINT      NOT NULL,
    work_date      DATE        NOT NULL,
    entry_at       TIMESTAMPTZ,
    lunch_start_at TIMESTAMPTZ,
    lunch_end_at   TIMESTAMPTZ,
    exit_at        TIMESTAMPTZ,
    CONSTRAINT fk_work_session_user FOREIGN KEY (id_user) REFERENCES users (id),
    CONSTRAINT uk_work_session_user_date UNIQUE (id_user, work_date)
);

CREATE INDEX idx_work_session_user_date ON work_session (id_user, work_date);

-- ---------------------------------------------------------------------------
-- Impostazioni per-utente in formato chiave/valore.
--   cod_settings es. 'home_url', 'task_base_url'
-- ---------------------------------------------------------------------------
CREATE TABLE settings (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user      BIGINT       NOT NULL,
    cod_settings VARCHAR(100) NOT NULL,
    value        VARCHAR(500) NOT NULL,
    CONSTRAINT fk_settings_user FOREIGN KEY (id_user) REFERENCES users (id),
    CONSTRAINT uk_settings_user_cod UNIQUE (id_user, cod_settings)
);
