-- ============================================================================
-- Consuntiver - nuovo schema (Supabase / PostgreSQL)
-- Riorganizzazione delle tabelle. Decisioni concordate:
--   - Timer/presenze: mantenuto (tabella work_session)
--   - task: per-utente, con anno di validita'
--   - settings: per-utente, in formato chiave/valore
--   - attivita' -> task: sia automatico dal testo (#codice) sia selezione manuale
-- Convenzioni: snake_case, chiavi esterne id_user/id_task, timestamp in UTC
-- (timestamptz), nomi temporali con suffisso _at.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Utenti registrati che possono accedere all'applicazione
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50)  NOT NULL,
    password   VARCHAR(255) NOT NULL,          -- hash BCrypt
    email      VARCHAR(255),                   -- facoltativo
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email    UNIQUE (email)
);

-- ---------------------------------------------------------------------------
-- Task riutilizzabili (per-utente, con anno di validita').
--   cod_task = numero del ticket sul portale (es. 129671), facoltativo
--   I task possono essere creati a mano (task fissi) o automaticamente quando
--   un'attivita' cita un #codice non ancora presente.
-- ---------------------------------------------------------------------------
CREATE TABLE task (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user     BIGINT       NOT NULL,
    cod_task    VARCHAR(50),
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    year        INTEGER      NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_task_user FOREIGN KEY (id_user) REFERENCES users (id)
);

-- Evita duplicati automatici dello stesso ticket per utente/anno
-- (solo quando il codice e' valorizzato).
CREATE UNIQUE INDEX uk_task_user_cod_year
    ON task (id_user, cod_task, year) WHERE cod_task IS NOT NULL;

CREATE INDEX idx_task_user_year ON task (id_user, year);

-- ---------------------------------------------------------------------------
-- Attivita' = le righe principali (interruzioni giornaliere).
--   start_at = inizio (alla creazione), end_at = fine (NULL = in corso)
--   id_task  = task collegato (NULL per righe senza task, es. "Pausa pranzo")
-- ---------------------------------------------------------------------------
CREATE TABLE activity (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user     BIGINT        NOT NULL,
    id_task     BIGINT,
    start_at    TIMESTAMPTZ   NOT NULL,
    end_at      TIMESTAMPTZ,
    description VARCHAR(2000) NOT NULL,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT fk_activity_user FOREIGN KEY (id_user) REFERENCES users (id),
    CONSTRAINT fk_activity_task FOREIGN KEY (id_task) REFERENCES task (id)
);

CREATE INDEX idx_activity_user_start ON activity (id_user, start_at);
CREATE INDEX idx_activity_user_open  ON activity (id_user, end_at);
CREATE INDEX idx_activity_task       ON activity (id_task);

-- ---------------------------------------------------------------------------
-- Sessioni di presenza (timbrature): il timer Inizio/Pausa e il contatore 8h.
--   clock_out NULL = sessione ancora aperta ("in servizio")
-- ---------------------------------------------------------------------------
CREATE TABLE work_session (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user   BIGINT      NOT NULL,
    clock_in  TIMESTAMPTZ NOT NULL,
    clock_out TIMESTAMPTZ,
    CONSTRAINT fk_work_session_user FOREIGN KEY (id_user) REFERENCES users (id)
);

CREATE INDEX idx_work_session_user_in ON work_session (id_user, clock_in);

-- ---------------------------------------------------------------------------
-- Impostazioni per-utente in formato chiave/valore.
--   cod_settings es. 'home_url', 'task_base_url'
-- ---------------------------------------------------------------------------
CREATE TABLE settings (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user      BIGINT       NOT NULL,
    cod_settings VARCHAR(100) NOT NULL,
    value        VARCHAR(500) NOT NULL,
    CONSTRAINT fk_settings_user FOREIGN KEY (id_user) REFERENCES users (id),
    CONSTRAINT uk_settings_user_cod UNIQUE (id_user, cod_settings)
);
